# Generated by Django 2.2.9 on 2022-03-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220330_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Choose what your post is about (not necessary)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Group'),
        ),
    ]
