# Generated by Django 4.0.4 on 2022-04-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_group_slug_alter_post_author_alter_post_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/', verbose_name='Image'),
        ),
    ]
