# Generated by Django 2.2.16 on 2022-05-11 16:12

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220511_1909'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique follower',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique following',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='check follower is not following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique following'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('user')), name='check following'),
        ),
    ]
