# Generated by Django 2.2.16 on 2022-05-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20220511_1915'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique following',
        ),
    ]
