# Generated by Django 2.2.16 on 2022-05-11 16:30

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20220511_1929'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('user')), name='check following'),
        ),
    ]
